/*
 * PUBLIC_VECTORS.H
 * 
 * This file contains the 'Answer Key' for the DoA project.
 * These vectors are generated by a Python script (perfect math) to serve as
 * the Ground Truth for your C implementation.
 * 
 * Usage:
 * 1. Use the macros below to configure your algorithm (N, FS, Spacing).
 * 2. In your test harness, pass these arrays to calculate_doa_angle_2mic().
 * 3. Verify that your output matches the angle in the variable name.
 */

#ifndef PUBLIC_VECTORS_H
#define PUBLIC_VECTORS_H

#include <stdint.h>

/* Rig Configuration Constants */
#define PUBLIC_VECTORS_FS   100000    // Sample Rate (Hz)
#define PUBLIC_VECTORS_N    500      // Buffer Length (Samples)
#define PUBLIC_VECTORS_D_MM 40.0     // Microphone Spacing (mm)

/* Test Case: 0 Degrees */
extern const int16_t test_0_deg_mic_left[500];
extern const int16_t test_0_deg_mic_right[500];

/* Test Case: 30 Degrees */
extern const int16_t test_30_deg_mic_left[500];
extern const int16_t test_30_deg_mic_right[500];

/* Test Case: -45 Degrees */
extern const int16_t test_minus_45_deg_mic_left[500];
extern const int16_t test_minus_45_deg_mic_right[500];

/* Test Case: 0 Degrees */
extern const int16_t test_0_deg_noisy_mic_left[500];
extern const int16_t test_0_deg_noisy_mic_right[500];

/* Test Case: 0 Degrees */
extern const int16_t test_0_deg_quiet_mic_left[500];
extern const int16_t test_0_deg_quiet_mic_right[500];

/* Test Case: 85 Degrees */
// extern const int16_t test_85_deg_mic_left[500];
// extern const int16_t test_85_deg_mic_right[500];

/* Test Case: -70 Degrees */
// extern const int16_t test_minus_70_deg_mic_left[500];
// extern const int16_t test_minus_70_deg_mic_right[500];

/* Test Case: 45 Degrees */
// extern const int16_t test_45_deg_noisy_mic_left[500];
// extern const int16_t test_45_deg_noisy_mic_right[500];


#endif
